---
title: "Group 11: Analysis of Prostate Cancer Data"
format: revealjs
editor: visual
---

## Introduction {.centered}

Our analysis exploits data from a randomised clinical trial by Byar & Greene that compares treatment of patients with prostate cancer in stages 3 and 4.  Treatment consisted of different doses of diethylstilbestrol (DES). Our aim is to investigate correlations, trends, or predictive models related to prostate cancer and patient outcomes.
Data are publicly available in : https://hbiostat.org/data/repo/prostate.xls

## Materials and Methods {.centered}

The initial dataset contains information related to 502 observations of patients with prostate cancer across 18 variables. These variables encompass diverse information including patient demographics, medical history, treatment received, and health status. 

The raw data were:
+ loaded, 
+ cleaned  
+ augmented
+ described
+ modelled.
and the process of arriving at results is done in a reproducible manner.

# Tidy data


## Results {.centered}

# Cause of Death across Age Groups

# PCA 

# Modelling


## Discussion {.centered}